name: Publish NPM Package

on:
  push:
    branches: [ "main" ]

env:
  NPM_REGISTRY_URL: https://registry.npmjs.org
  NVMRC_FILE: ./config/.nvmrc

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.NVMRC_FILE }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: Install dependencies
        run: npm  ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Audit dependencies
        run: npm audit

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

      - name: Build code
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
